services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: web_app
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
     - 127.0.0.1:8080:8080
     - 127.0.0.1:8081:8081
    restart: on-failure
    networks:
      - default
      - internal_network
    depends_on:
      - db
    cpus: "1.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/category/roots"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  db:
    image: postgres:15-alpine
    container_name: db
    hostname: database_host
    expose:
      - 5432
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: callboard_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d callboard_db"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db_data:
    name: db_data

networks:
  internal_network:
    internal: true
  default:
